## NumPy

NumPy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [56]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [57]:
import numpy as np

In [58]:
# Creating an one dimensional array using numpy

arr1 = np.array([1,2,3,4,5])
print(f"The array created is : {arr1}")
print(f"The data type of array is : {type(arr1)}")
print(f"The shape of the array is : {arr1.shape}")

The array created is : [1 2 3 4 5]
The data type of array is : <class 'numpy.ndarray'>
The shape of the array is : (5,)


In [59]:
# Reshaping an array
arr = np.array([1,2,3,4,5,6,7,8,9,10])

# Since total number of elements are 10 it can be reshaped into
# 1x10 / 10x1 / 2x5 / 5x2
arr = arr.reshape((2,5))
print(f"After reshaping into 2x5 : \n{arr}")

arr = arr.reshape((5,2))
print(f"\nAfter reshaping into 5x2 : \n{arr}")

After reshaping into 2x5 : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

After reshaping into 5x2 : 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [60]:
# Creating an array with a range of elements
# param1 -> starting number (included)
# param2 -> ending number (excluded)
# param3 -> step (difference between consecutive elements)

arr = np.arange(0,12,2)
print(f"Created array is : {arr}")


arr = arr.reshape((2,3))
print(f"\nArray after reshaping to 2x3 : \n{arr}")


Created array is : [ 0  2  4  6  8 10]

Array after reshaping to 2x3 : 
[[ 0  2  4]
 [ 6  8 10]]


In [61]:
# Creating an n-dimensional array with 1's 

arr = np.ones(10)
print(f"One dimensional array with size 10 is : \n{arr}")

arr = np.ones((3,4))
print(f"\nTwo dimensional array with size 3x4 is : \n{arr}")

One dimensional array with size 10 is : 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Two dimensional array with size 3x4 is : 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [62]:
# Creating an identity matrix of size n

arr = np.eye(5)
print(f"Identity matrix of size 5x5 is \n{arr}")

Identity matrix of size 5x5 is 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [63]:
# Understanding properties of a numpy array

arr = np.array([[1,2,3],[4,5,6]])

print(f"Array is : \n{arr}")
print(f"\nShape of the array is : {arr.shape}")
print(f"Number of dimensions of the array is : {arr.ndim}")
print(f"Total number of elements in the array is : {arr.size}")
print(f"Data type of all elements in array is : {arr.dtype}")
print(f"Total size (in bytes) of the array is : {arr.itemsize}")

Array is : 
[[1 2 3]
 [4 5 6]]

Shape of the array is : (2, 3)
Number of dimensions of the array is : 2
Total number of elements in the array is : 6
Data type of all elements in array is : int64
Total size (in bytes) of the array is : 8


### Element wise arithmetic operations using NumPy

In [64]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([50,40,30,20,10,0])

print(f"Element wise addition of {arr1} and {arr2} is {arr1 + arr2}")
print(f"Element wise subtraction of {arr1} and {arr2} is {arr1-arr2}")

print(f"\nElement wise multiplication of {arr1} and {arr2} is {arr1 * arr2}")
print(f"Element wise division of {arr2} by {arr1} is {arr2/arr1}")

Element wise addition of [1 2 3 4 5 6] and [50 40 30 20 10  0] is [51 42 33 24 15  6]
Element wise subtraction of [1 2 3 4 5 6] and [50 40 30 20 10  0] is [-49 -38 -27 -16  -5   6]

Element wise multiplication of [1 2 3 4 5 6] and [50 40 30 20 10  0] is [50 80 90 80 50  0]
Element wise division of [50 40 30 20 10  0] by [1 2 3 4 5 6] is [50. 20. 10.  5.  2.  0.]


### Universal functions
The functions which will apply for all elements in the NumPy array

In [65]:
arr = np.array([1,2,3,4,5,6])

print(f"Square rooted array {arr} is : {np.sqrt(arr)}")
print(f"Exponential array of {arr} is : {np.exp(arr)}")
print(f"Sine of the array {arr} is : {np.sin(arr)}")
print(f"Natural logarithm of array {arr} is : {np.log(arr)}")


Square rooted array [1 2 3 4 5 6] is : [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential array of [1 2 3 4 5 6] is : [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
Sine of the array [1 2 3 4 5 6] is : [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Natural logarithm of array [1 2 3 4 5 6] is : [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


### Array indexing

In [66]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

for row_number in range(len(arr)):
    for column_number in range(len(arr[row_number])):
        print(f"({row_number},{column_number}):{arr[row_number][column_number]}",end=" "*5)
    print("\n")

(0,0):1     (0,1):2     (0,2):3     (0,3):4     

(1,0):5     (1,1):6     (1,2):7     (1,3):8     

(2,0):9     (2,1):10     (2,2):11     (2,3):12     



In [67]:
# Printing rows

print(f"First row is: {arr[0]}") # Prints first row
print(f"Second row is : {arr[1]}") # Prints second row

First row is: [1 2 3 4]
Second row is : [5 6 7 8]


In [68]:
# Printing elements
print(f"Element at first row and first column is : {arr[0][0]}")
print(f"Element at second row third column is : {arr[1][2]}")

Element at first row and first column is : 1
Element at second row third column is : 7


### Array slicing

In [69]:
arr = np.arange(1,17).reshape((4,4))

print(f"Entire array without first row is : \n{arr[1:]}")
print(f"\nEntire array without last row is: \n{arr[:3]}")
print(f"\nEntire array without first and last row is : \n{arr[1:3]}")

Entire array without first row is : 
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Entire array without last row is: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Entire array without first and last row is : 
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [70]:
# Trying to get matrix [[3,4],[7,8]] from the array
print(f"Array after slicing out last two rows : \n{arr[:2]}")

# Now we are interested only in last two columns so, we need slicing 2: from here
print(f"\nAfter slicing out last two rows and first two columns : \n{arr[:2,2:]}")

Array after slicing out last two rows : 
[[1 2 3 4]
 [5 6 7 8]]

After slicing out last two rows and first two columns : 
[[3 4]
 [7 8]]


### Modifying elements in array

In [71]:
# Since NumPy arrays are mutable, we can modify their values
print(f"Original array is : \n{arr}")

# Modifying element at first row first column
arr[0][0] = 1024

print(f"\nArray after modifying element at (0,0) is : \n{arr}")

Original array is : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Array after modifying element at (0,0) is : 
[[1024    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]
 [  13   14   15   16]]


### Statistical operations

In [74]:
arr = np.array([1,2,3,4,5,6])

mean = np.mean(arr)
standard_deviation = np.std(arr)
variance = np.var(arr)
normalized_data = (arr - mean)/standard_deviation

print(f"The mean of {arr} is : {mean}")
print(f"The standard deviation of {arr} is : {standard_deviation}")
print(f"The variance of the {arr} is : {variance}")
print(f"Normalized array {arr} is : {normalized_data}")

The mean of [1 2 3 4 5 6] is : 3.5
The standard deviation of [1 2 3 4 5 6] is : 1.707825127659933
The variance of the [1 2 3 4 5 6] is : 2.9166666666666665
Normalized array [1 2 3 4 5 6] is : [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


### Logical operations

In [81]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(f"Logical operation of elements > 5 is : {arr > 5}")
print(f"Filtered array with logical operator elements > 5 is : {arr[arr > 5]}")
print(f"Filtered array with elements >= 5 and elements <= 8 is : {arr[(arr >=5) & (arr <= 8)]}")

Logical operation of elements > 5 is : [False False False False False  True  True  True  True  True]
Filtered array with logical operator elements > 5 is : [ 6  7  8  9 10]
Filtered array with elements >= 5 and elements <= 8 is : [5 6 7 8]
